### PR TITLE
feat: Add ThermoFisher Qubit4 Adapter

### PR DESCRIPTION
**Pull request by poojabalaji05**
Add adapter for the ThermoFisher Qubit4 instrument. The adapter handles both XLSX and CSV exports of the instrument data.
The adapter uses [spectrophotometry](https://github.com/Benchling-Open-Source/allotropy/blob/main/src/allotropy/allotrope/schemas/adm/spectrophotometry/BENCHLING/2023/12/spectrophotometry.schema.json) schema of allotropy.

### CODE REVIEW

**Review by nathan-stender — APPROVED** [review]

**Comment by nathan-stender** [comment]
@poojabalaji05 thank you for catching default null issue in custom info doc!

I noticed the null items after you merged dev in this PR: https://github.com/Benchling-Open-Source/allotropy/pull/492 

This is due to a recent change by me for how we handle removing nulls, I guess we didn't have a test case where we were adding null items to custom info doc until now!

I think once this PR is merged in, we can sync the test results in the other PR and it will remove the nulls.

**Comment by nathan-stender** [comment]
@poojabalaji05 looks like some typing issues here too.

**Comment by poojabalaji05** [comment]
@nathan-stender 
I've resolved the linting issues. Also, I noticed that the Tests failed because currently the parser's release state is not updated to 'recommended' which is expected and currently it is in "working draft" and also this is not added to the readme.md file. As we discussed early, I assume you'll take care of this from your end else let us know I can also help on this.

**Comment by nathan-stender** [comment]
@poojabalaji05  for the README test, you will need to update the README in this PR for the test to pass, e.g.

```
### Candidate Release
  - Qiacuity dPCR
  - Mabtech Apex

### Working Draft
  - Thermo Fisher Qubit 4
```

**Comment by nathan-stender** [comment]
@poojabalaji05 if you pull past this PR: https://github.com/Benchling-Open-Source/allotropy/pull/507, you can run `hatch run scripts:update-readme` to update the README file!

**Comment by poojabalaji05** [comment]
@nathan-stender 
I have updated the `README.md` file by adding the parser and also included the vendor in the `NON_READY_PARSERS` dictionary to avoid test failure in `test_vendor_release_state` function.

I noticed that the test script structure has been modified, so I have made the necessary adjustments from my end as well.

**Review by nathan-stender — APPROVED** [review]

**Comment by nathan-stender** [comment]
@poojabalaji05 merged!

**Pull request merged**
