### PR TITLE
feat: add support for extracting processed data values and instrument spec

### PR DESCRIPTION
**Pull request by trevorHalumDG**
- Example parser now extracts the processed data values from the csv
- Fixed the layout of cell_data by transposing the data frame
- Added support for extracting the instrument spec

### CODE REVIEW

**Review by nathan-stender — CHANGES_REQUESTED** [review]
Can you please add a description and more descriptive title to this before we approve/merge?

I would normally ask to add to CHANGELOG too, but since this is an example I don't think we need that in this case.

**Review by nathan-stender — APPROVED** [review]

**Comment by gvwilson** [comment]
happy to take this one on

**Comment by trevorHalumDG** [comment]
Hi! Apologies again for the delay. I've included in this PR the support for extracting the instrument specification from the csv file, the lack thereof was causing the tests to fail.

**Review by mdlu — APPROVED** [review]
this looks good to me but I'm not sure if you wanted to merge it yet? give me a ping once you do

**Comment by trevorHalumDG** [comment]
@mdlu thanks, please merge when you can.

**Pull request merged**
