### PR TITLE
Chore: Adding SMP test data - examples of exports containing partial plates

### PR DESCRIPTION
**Pull request by LimulusPolyphemus**

### CODE REVIEW

**Review by nathan-stender — CHANGES_REQUESTED** [review]
Thanks for adding the test data!

That said, can you please add something to these names indicating that their test case, e.g. `MD_SMP_absorbance_endpoint_partial_plate_example01.txt` ?

We've been lax with this, but it would be good to know what test cases are testing for future reference.

**Comment by LimulusPolyphemus** [comment]
@nathan-stender I updated the file names to reflect the test case.

**Comment by nathan-stender** [comment]
@LimulusPolyphemus I think you need to push the commit

**Comment by LimulusPolyphemus** [comment]
@nathan-stender I did. The commit is on the branch, but it's not appearing on the PR for some reason, hmmm

**Review by nathan-stender — APPROVED** [review]

**Comment by nathan-stender** [comment]
The change appeared 👍

**Pull request merged**
